version: '3'

services:

  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    container_name: homebridge
    volumes:
      - .config:/homebridge
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Madrid
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8081

  mosquitto:
    build: .
    image: monstrenyatko/rpi-mosquitto
    container_name: mosquitto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .mosquitto-config:/config:ro
      - .mosquitto-data:/data:rw
    ports:
      - "1883:1883"
      - "9001:9001"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped


  grafana:
    container_name: grafana
    image: teslamate/grafana:latest
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3000:3000
    depends_on:
      - "database"
    volumes:
      - .grafana-data:/var/lib/grafana
      
  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    ports:
     - "8086:8086"
    volumes:
      - .data_influxdb:/var/lib/influxdb

  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy

    environment:
      - TZ=Europe/Madrid
      - PASSWORD=xxxx
      - WG_HOST=192.168.68.13
      - SERVERURL=yaju.myds.me

    volumes:
      - .wireguard.config/config:/etc/wireguard
      - .wireguard.modules:/lib/modules
    ports:
      - "8100:51820/udp"
      - "8101:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
 
